from __future__ import annotations

from zhishu_dualarm_lab.tasks.dualarm_tabletop.constants import (
    ACTION_DIM,
    ACTION_SPACE,
    ARM_ACTION_DELTA_SCALE,
    ARM_JOINT_NAMES,
    CAMERA_BODY_SIZE,
    DECIMATION,
    EPISODE_LENGTH_S,
    EXTERNAL_CAMERA_HEIGHT,
    EXTERNAL_CAMERA_WIDTH,
    HEAD_CAMERA_LINK_NAME,
    HEAD_CAMERA_OFFSET_POS,
    HEAD_CAMERA_OFFSET_ROT,
    JOINT_VELOCITY_SCALE,
    LEFT_TCP_LINK_NAME,
    LEFT_TCP_NAME,
    LEFT_TCP_OFFSET_POS,
    LEFT_TCP_OFFSET_ROT,
    LEFT_WRIST_CAMERA_OFFSET_POS,
    LEFT_WRIST_CAMERA_OFFSET_ROT,
    OBSERVATION_SPACE,
    POLICY_PROMPT,
    PACKAGE_ROOT,
    RESET_JOINT_NOISE,
    RIGHT_TCP_LINK_NAME,
    RIGHT_TCP_NAME,
    RIGHT_TCP_OFFSET_POS,
    RIGHT_TCP_OFFSET_ROT,
    RIGHT_WRIST_CAMERA_OFFSET_POS,
    RIGHT_WRIST_CAMERA_OFFSET_ROT,
    SIM_DT,
    WAIST_CAMERA_LINK_NAME,
    WAIST_CAMERA_OFFSET_POS,
    WAIST_CAMERA_OFFSET_ROT,
)

ENV_ID = "Zhishu-DualArm-RobotWithPlate-Direct-v0"
PLATE_USD_PATH = PACKAGE_ROOT / "assets/plate/plate.usd"
PLATE_INIT_POS = (0.30, 0.0, 0.95)
PLATE_INIT_ROT = (1.0, 0.0, 0.0, 0.0)
